baseurl: "https://xd-con.org/imagexd-2019"
title: "ImageXD 2019"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "ImageXD 2019"
  Description: "Images Across Domains"
  Date: "September 11–13"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Berkeley Institute for Data Science"
  Address: "190 Doe Library, UC Berkeley Campus"
  City:  "Berkeley"
  State: "California"
#  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - organizers
#    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    organizers: "Organizers"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Applications Now Open"
    link: "#"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
#  ForkButton:
#    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Berkeley Institute for Data Science"
      logo: "/img/BIDS.png"
      url: "https://bids.berkeley.edu"

  # List of Partners
  # Partners:
  #   - name: "Hugo"
  #     logo: "/img/hugo.jpg"
  #     url: "https://gohugo.io"
  #   - name: "BrazilJS"
  #     logo: "/img/partner.png"
  #     url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - day: "Wednesday (11 Sep)"
      slots:
        - name: "Check-in / Breakfast"
          time: "09:00"

    - day: "Thursday (12 Sep)"
      slots:
        - name: "Breakfast"
          time: "09:00"

    - day: "Friday (13 Sep)"
      slots:
        - name: "Breakfast"
          time: "09:00"

    # - name: "Linus Torvalds"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Linux Foundation"
    #   link:
    #     href: "http://twitter.com/linus"
    #     text: "@linus"
    #   presentation:
    #     title: "Digging into a Linux Kernel"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "10h00"

  Organizers:
    - name: "Daniela Ushizima"
      affiliation: "LBNL / UC Berkeley"
    - name: "Maryana Alegro"
      affiliation: "UCSF / UC Berkeley"
    - name: "Kevin Keys"
      affiliation: "UCSF / UC Berkeley"
    - name: "Henry Pinkard"
      affiliation: "UC Berkeley"
    - name: "Stéfan van der Walt"
      affiliation: "UC Berkeley"
